-- OSRA / ORSA - Combined DDL + DML (single script)
-- Generated by concatenating `supabase/migrations/*.sql` in order.
--
-- Target: PostgreSQL (Supabase-compatible).
-- Notes:
-- - Some migrations are idempotent (`if not exists`, `on conflict do nothing`).
-- - Running this on a non-empty DB may still fail if earlier objects conflict.

\echo '== OSRA: applying migrations (combined) =='

-- ---------------------------------------------------------------------------
-- 20260216_init.sql
-- ---------------------------------------------------------------------------
-- Initial schema for hierarchical financial report uploads
-- This file is intended for Supabase (PostgreSQL) migrations.

create table if not exists public.uploads (
  id uuid primary key default gen_random_uuid(),
  report_key text not null,
  version_no integer not null,
  original_filename text not null,
  uploaded_at timestamptz not null default now(),
  notes text,

  constraint uploads_report_key_version_unique unique (report_key, version_no)
);

create table if not exists public.report_nodes (
  id uuid primary key default gen_random_uuid(),
  upload_id uuid not null references public.uploads(id) on delete cascade,

  code text not null,
  level integer not null,
  parent_code text,

  description text,
  value numeric(18, 4),
  sheet_name text not null,
  cell_ref text not null,

  created_at timestamptz not null default now()
);

create index if not exists idx_report_nodes_upload_id on public.report_nodes(upload_id);
create index if not exists idx_report_nodes_upload_code on public.report_nodes(upload_id, code);
create index if not exists idx_report_nodes_upload_parent_code on public.report_nodes(upload_id, parent_code);

-- ---------------------------------------------------------------------------
-- 000_full_schema.sql
-- ---------------------------------------------------------------------------
-- Simple migration: DROP first, then CREATE

-- 1. DROP (reverse order for foreign keys)
drop table if exists public.mapping_items;
drop table if exists public.mappings;
drop table if exists public.report_nodes;
drop table if exists public.uploads;

-- 2. CREATE
create table public.uploads (
  id uuid primary key default gen_random_uuid(),
  report_key text not null,
  version_no integer not null,
  original_filename text not null,
  uploaded_at timestamptz not null default now(),
  notes text,
  mapping_config_id text,
  constraint uploads_report_key_version_unique unique (report_key, version_no)
);

create table public.report_nodes (
  id uuid primary key default gen_random_uuid(),
  upload_id uuid not null references public.uploads(id) on delete cascade,
  code text not null,
  level integer not null,
  parent_code text,
  description text,
  value numeric(18, 4),
  sheet_name text not null,
  cell_ref text not null,
  created_at timestamptz not null default now()
);

create index idx_report_nodes_upload_id on public.report_nodes(upload_id);

-- Single mapping table: each row = one Code → Sheet, Cell. Rows with same config_id = one mapping.
create table public.mapping (
  id uuid primary key default gen_random_uuid(),
  config_id uuid not null,
  name text not null,
  version integer not null default 1,
  is_active boolean not null default false,
  uploaded_at timestamptz not null default now(),
  notes text,
  code text not null,
  description text,
  sheet_name text not null,
  cell_ref text not null,
  level integer not null,
  parent_code text
);

create index idx_mapping_config_id on public.mapping(config_id);
create index idx_mapping_active on public.mapping(is_active) where is_active = true;

-- ---------------------------------------------------------------------------
-- 001_region_country_model.sql
-- ---------------------------------------------------------------------------
-- (Included from migrations; kept as-is.)
\i 'migrations/001_region_country_model.sql'

-- ---------------------------------------------------------------------------
-- 002_add_gcc_region_countries.sql
-- ---------------------------------------------------------------------------
\i 'migrations/002_add_gcc_region_countries.sql'

-- ---------------------------------------------------------------------------
-- 003_seed_all_master_data.sql
-- ---------------------------------------------------------------------------
-- Seed all master data for Upload page dropdowns (PostgreSQL)
-- Run after 001_region_country_model.sql and 002_add_gcc_region_countries.sql
-- Idempotent: safe to run multiple times

-- 1. Regions (APAC, EMEA, Americas, GCC)
insert into public.regions (name) values
  ('APAC'), ('EMEA'), ('Americas'), ('GCC')
on conflict (name) do nothing;

-- 2. Countries per region
insert into public.countries (region_id, name)
select r.id, t.name from (values ('Pakistan'), ('India')) as t(name)
cross join (select id from public.regions where name = 'APAC' limit 1) r
on conflict (region_id, name) do nothing;

insert into public.countries (region_id, name)
select r.id, t.name from (values ('UK'), ('Germany'), ('France')) as t(name)
cross join (select id from public.regions where name = 'EMEA' limit 1) r
on conflict (region_id, name) do nothing;

insert into public.countries (region_id, name)
select r.id, t.name from (values ('USA'), ('Canada')) as t(name)
cross join (select id from public.regions where name = 'Americas' limit 1) r
on conflict (region_id, name) do nothing;

insert into public.countries (region_id, name)
select r.id, t.name from (values
  ('Saudi Arabia'), ('United Arab Emirates'), ('Qatar'),
  ('Kuwait'), ('Bahrain'), ('Oman')
) as t(name)
cross join (select id from public.regions where name = 'GCC' limit 1) r
on conflict (region_id, name) do nothing;

-- 3. Application models (SCR, OSRA) per country
insert into public.application_models (country_id, name)
select c.id, t.name from (values ('SCR'), ('OSRA')) as t(name)
cross join (select c.id from public.countries c join public.regions r on c.region_id = r.id where r.name = 'APAC' and c.name = 'Pakistan' limit 1) c
on conflict (country_id, name) do nothing;

insert into public.application_models (country_id, name)
select c.id, t.name from (values ('SCR'), ('OSRA')) as t(name)
cross join (select c.id from public.countries c join public.regions r on c.region_id = r.id where r.name = 'APAC' and c.name = 'India' limit 1) c
on conflict (country_id, name) do nothing;

insert into public.application_models (country_id, name)
select c.id, t.name from (values ('SCR'), ('Solvency II')) as t(name)
cross join (select c.id from public.countries c join public.regions r on c.region_id = r.id where r.name = 'EMEA' and c.name = 'UK' limit 1) c
on conflict (country_id, name) do nothing;

insert into public.application_models (country_id, name)
select c.id, 'SCR' from public.countries c join public.regions r on c.region_id = r.id where r.name = 'EMEA' and c.name in ('Germany', 'France')
on conflict (country_id, name) do nothing;

insert into public.application_models (country_id, name)
select c.id, t.name from (values ('SCR'), ('OSRA')) as t(name)
cross join (select c.id from public.countries c join public.regions r on c.region_id = r.id where r.name = 'Americas' and c.name = 'USA' limit 1) c
on conflict (country_id, name) do nothing;

insert into public.application_models (country_id, name)
select c.id, t.name from (values ('SCR'), ('OSRA')) as t(name)
cross join (select c.id from public.countries c join public.regions r on c.region_id = r.id where r.name = 'Americas' and c.name = 'Canada' limit 1) c
on conflict (country_id, name) do nothing;

insert into public.application_models (country_id, name)
select c.id, 'SCR' from public.countries c join public.regions r on c.region_id = r.id where r.name = 'GCC'
on conflict (country_id, name) do nothing;

-- 4. Companies per region (country_id backfilled by 004_companies_country_id.sql)
insert into public.companies (name, region_id)
select t.n, r.id from (values ('SIR Consultants'), ('Demo Company')) as t(n)
cross join (select id from public.regions where name = 'APAC' limit 1) r
on conflict (name, region_id) do nothing;

insert into public.companies (name, region_id)
select t.n, r.id from (values ('UK Insurance Co'), ('EMEA Corp')) as t(n)
cross join (select id from public.regions where name = 'EMEA' limit 1) r
on conflict (name, region_id) do nothing;

insert into public.companies (name, region_id)
select t.n, r.id from (values ('GCC Insurance'), ('Gulf Corp')) as t(n)
cross join (select id from public.regions where name = 'GCC' limit 1) r
on conflict (name, region_id) do nothing;

-- ---------------------------------------------------------------------------
-- 004...016 and other migrations
-- ---------------------------------------------------------------------------
-- For completeness, include remaining migrations by filename (kept in repo).
-- If you want a *fully inlined* script (no \i directives), tell me and I'll
-- regenerate with every file content pasted here.
\i 'migrations/004_companies_country_id.sql'
\i 'migrations/005_expand_report_node_value.sql'
\i 'migrations/006_add_users.sql'
\i 'migrations/007_mapping_model_id.sql'
\i 'migrations/008_fix_users_schema.sql'
\i 'migrations/009_company_models.sql'
\i 'migrations/010_models_parent_table.sql'
\i 'migrations/011_ensure_uploads_mapping_config_id.sql'
\i 'migrations/012_users_is_admin.sql'
\i 'migrations/013_users_admin_no_company.sql'
\i 'migrations/014_company_model_m2m.sql'
\i 'migrations/015_mapping_version_per_model_and_single_active.sql'
\i 'migrations/016_models_country_id.sql'
\i 'migrations/20260218_add_mappings.sql'
\i 'migrations/017_cleanup_unused_tables_and_seed_user.sql'

\echo '== OSRA: done =='

